

function  write_parameters_single_bspline ( HistBins, NumRes, NumIter,SpatSam, GridSpac )
 
% Inouts shoudl all be strings

filename = fullfile(transformationParametersDir, '/parameters_single_bspline.txt');
%% Put default values so you don't always have to reset the changes you made
% All values are taken from the default Elastix values

if strcmp( HistBins,'') ; HistBins = '32';end
if strcmp( NumRes,'') ; NumRes = '3';end
if strcmp( NumIter,'') ; NumIter = '500';end   % In elastix maar 100 maar wij nemen dit vast
if strcmp( SpatSam,'') ; SpatSam = '2000';end  % In elastix 5000 maar wij hebben afbeeldingen van +- 8000 pixels
if strcmp( GridSpac,'') ; GridSpac = '16';end  % In mm



%% Start writing
cell_parameters={...
'(FixedInternalImagePixelType "float") ',...
'(MovingInternalImagePixelType "float") ',...
'(UseDirectionCosines "true") ',...
'(Registration "MultiResolutionRegistration") ',...
'(Interpolator "BSplineInterpolator") ',...
'(ResampleInterpolator "FinalBSplineInterpolator") ',...
'(Resampler "DefaultResampler") ',...
'(FixedImagePyramid "FixedRecursiveImagePyramid") ',...
'(MovingImagePyramid "MovingRecursiveImagePyramid")' ,...
'(Optimizer "AdaptiveStochasticGradientDescent") ',...
'(Transform "BSplineTransform") ',...
'(Metric "AdvancedMattesMutualInformation" )',...
['(NumberOfHistogramBins ' HistBins ')'],...
'(AutomaticScalesEstimation "true") ',...
['(FinalGridSpacingInPhysicalUnits ' GridSpac  ')  '],...
'(HowToCombineTransforms "Compose")' ,...
'(ErodeMask "true") ',...
['(NumberOfResolutions ' NumRes ') '],...
['(MaximumNumberOfIterations ' NumIter ')'] ,...
'(MaximumStepLength 1) ',...
['(NumberOfSpatialSamples ' SpatSam ')'] ,...
'(NewSamplesEveryIteration "true")' ,...
'(ImageSampler "Random")',...
'(BSplineInterpolationOrder "1")' ,...
'(FinalBSplineInterpolationOrder "3")' ,...
'(DefaultPixelValue 0) ',...
'(WriteResultImage "false")' ,...
'(ResultImagePixelType "float")' ,...
'(ResultImageFormat "nii") ',...
'(ShowExactMetricValue "true" "true")'};


 
fid = fopen(filename, 'w');
[nrows,ncols]= size(cell_parameters);
for row=1:nrows
fprintf(fid, '%s \n', cell_parameters{row,:});

end


