

function  write_parameters_single_affine ( HistBins, NumRes,NumIter,SpatSam )
 
% Inouts shoudl all be strings
filename = fullfile(transformationParametersDir, '/parameters_single_affine.txt');

%% Put default values so you don't always have to reset the changes you made
% All values are taken from the default Elastix values

if strcmp( HistBins,'') ; HistBins = '32';end
if strcmp( NumRes,'') ; NumRes = '3';end
if strcmp( NumIter,'') ; NumIter = '500';end   % In elastix maar 100 maar wij nemen dit vast ( Zie ook thesis L. Vandewinckele )
if strcmp( SpatSam,'') ; SpatSam = '2000';end  % In elastix 5000 maar wij hebben afbeeldingen van +- 8000 pixels


%% Start writing
cell_parameters={...
'(FixedInternalImagePixelType "float") ',...
'(MovingInternalImagePixelType "float") ',...
'(UseDirectionCosines "true") ',...
'(Registration "MultiResolutionRegistration") ',...
'(Interpolator "BSplineInterpolator") ',...
'(ResampleInterpolator "FinalBSplineInterpolator") ',...
'(Resampler "DefaultResampler") ',...
'(FixedImagePyramid "FixedRecursiveImagePyramid") ',...
'(MovingImagePyramid "MovingRecursiveImagePyramid")' ,...
'(Optimizer "AdaptiveStochasticGradientDescent") ',...
'(Transform "AffineTransform") ',...
'(Metric "AdvancedMattesMutualInformation" )',...
['(NumberOfHistogramBins ' HistBins ')'],...
'(AutomaticScalesEstimation "true") ',...
'(HowToCombineTransforms "Compose")' ,...
'(ErodeMask "true") ',...
['(NumberOfResolutions ' NumRes ') '],...
['(MaximumNumberOfIterations ' NumIter ')'] ,...
'(MaximumStepLength 1) ',...
['(NumberOfSpatialSamples ' SpatSam ')'] ,...
'(NewSamplesEveryIteration "true")' ,...
'(ImageSampler "Random")',...
'(BSplineInterpolationOrder "1")' ,...
'(FinalBSplineInterpolationOrder "3")' ,...
'(DefaultPixelValue 0) ',...
'(WriteResultImage "false")' ,...
'(ResultImagePixelType "float")' ,...
'(ResultImageFormat "nii") ',...
'(ShowExactMetricValue "true" "true")'};


 
fid = fopen(filename, 'w');
[nrows,ncols]= size(cell_parameters);
for row=1:nrows
fprintf(fid, '%s \n', cell_parameters{row,:});

end


