
function B0 = getShim(N, shimPar, MT, shimType, debug)

%GETSHIM calculate the B0 field generated by the active shimming on the SIEMENS MAGNETOM Terra 7T scanner. 
%   This method is based on shim testing performed by Jan Sedlacik on the LOCUS 7T facility (https://emckclac.sharepoint.com/sites/LSM7tmri/Physics/Forms/AllItems.aspx?viewid=a16a5958%2D0946%2D485c%2Daebd%2D0e2793fcab8c&id=%2Fsites%2FLSM7tmri%2FPhysics%2FTesting%5Fand%5Foptimisations)
%   [B0]=GETSHIM(X,ORDIM,{M})
%   * N is an array size
%   * MT is the orientation information of the array of size N, on which this shim is applied.
%   ** B0 is the resulting volumetric B0 field in the array geometry in units of Hz.
%
%   See also SHIMBASIS, TWIX2REC

if isempty(N); error('getShim:: Array size must be provided.');end
if nargin<2 || isempty(shimPar) ; error('getShim:: Shim parameters must be provided.');end
if nargin<3 || isempty(MT);warning('getShim:: MT orientation not provided. Zero shim returned.');B0 = zeros(N); return; end
if nargin<4 || isempty(shimType);shimType='active'; end
if nargin<5 || isempty(debug);debug=0; end

if ~isfield(shimPar,'shimOrder'); warning('getShim:: shimOrder not provided. Default value = 3 selected.'); shimPar.shimOrder = 3;end
if ~isfield(shimPar,'gamma'); warning('getShim:: gyromagnetic ration not provided. That of H+ selected = 42.58MHz/T'); shimPar.gamma = 42.58;end
if ~isfield(shimPar,'correctFact_mA2au')&& strcmp( shimType, 'active'); warning('getShim:: correctFact_mA2au not provided. Inaccurate estimate expected.');end
if ~isfield(shimPar,'crossTerms') && strcmp( shimType, 'active'); warning('getShim:: crossTerms not provided. Inaccurate estimate expected.');end

%%% HANDLE PASSIVE SHIM SETTINGS
if strcmp( shimType, 'passive')
    if debug; fprintf('Calculating passive shim.\n');end
    error('passive not implemented');
%     temp = shimPar; clear shimPar;
%     shimPar.shimCurrents_au = temp;
%     %Remove any factors in the shim parameters that relate to active shimming
%     if isfield(shimPar,'correctFact_mA2au'); shimPar = rmfield(shimPar, 'correctFact_mA2au');end
%     if isfield(shimPar,'crossTerms'); shimPar = rmfield(shimPar, 'crossTerms');end
elseif strcmp( shimType, 'tune-up')
    if debug;fprintf('Calculating tune-up shim.\n');end

    %Remove any factors in the shim parameters that relate to active shimming
    if isfield(shimPar,'correctFact_mA2au'); shimPar = rmfield(shimPar, 'correctFact_mA2au');end
    if isfield(shimPar,'crossTerms'); shimPar = rmfield(shimPar, 'crossTerms');end    
    
elseif strcmp( shimType, 'active')
    if debug;fprintf('Calculating active shim.\n');end
end

%%% CREATE SHIM BASIS
[B, ~, coefNameTerra ] = shimBasis(N, MT, shimPar.shimOrder);%In m^n %Includes the DC term

%%% CONVERT SCANNER SHIM CURRENTS TO SHIM BASIS PARAMETERS
shimCurrents = shimPar.shimCurrents_au;%In au
if isfield( shimPar , 'correctFact_mA2au'); shimCurrents = shimCurrents ./ shimPar.correctFact_mA2au;end%Converted to mA
if isfield( shimPar , 'crossTerms'); shimCurrents =  shimPar.crossTerms * shimCurrents;end % Converted to uT/m^n. Also increases the number of coeffiecients from 13 to >13
    
%%% APPLY COEFFICIENTS TO BASIS AND SUM

if size(shimCurrents,1)>size(B,4)
    warning('getShim:: Not all shim coils taken into account since shim basis not exhaustive enough.');
    nS = size(B,4);
elseif size(shimCurrents,1)<=size(B,4)
    nS = size(shimCurrents,1);
end
shimInd = 2:nS; %Offset also returned by scanner in shimCurrents_au but don't calculate

B0 = bsxfun(@times, dynInd(B, shimInd, 4), permute(  dynInd( shimCurrents,shimInd,1) , [2:4 1])  );% m^n *  uT/m^n = uT
B0 = multDimSum(B0,4);%In uT
B0 = shimPar.gamma *B0;%In Hz %gamma stored in Hz/uT = MHz/T (42.58 for H+)

%%% REPORT
if debug
    fprintf('\nShim terms included in the B0 shim field:\n' );
    fprintf('                                         %s\n', coefNameTerra{shimInd} );%Offset not included
end
end

